// src/services/mockdata.js

export const user = {
  id: 1,
  name: "Lê Đức Huy",
  email: "huy@example.com",
  balance: 12000000
};

export const transactions = [
  {
    id: "t001",
    type: "expense",
    category: "Đồ ăn & Đồ uống",
    note: "Ăn trưa quán cơm văn phòng",
    amount: 45000,
    currency: "VND",
    date: "2025-10-13",
    repeat: "never",
    imageUrl: "https://media-cdn-v2.laodong.vn/Storage/NewsPortal/2023/3/14/1157787/315951188_1580040079.jpg",
  },
  {
    id: "t002",
    type: "expense",
    category: "Di chuyển",
    note: "Đổ xăng xe Air Blade",
    amount: 70000,
    currency: "VND",
    date: "2025-10-12",
    repeat: "never",
    imageUrl: "https://example.com/images/fuel.jpg",
  },
  {
    id: "t003",
    type: "expense",
    category: "Hóa đơn & Phí",
    note: "Tiền điện tháng 10",
    amount: 920000,
    currency: "VND",
    date: "2025-10-10",
    repeat: "monthly",
    imageUrl: "https://example.com/images/electric-bill.jpg",
  },
  {
    id: "t004",
    type: "income",
    category: "Lương",
    note: "Lương tháng 10",
    amount: 8500000,
    currency: "VND",
    date: "2025-10-05",
    repeat: "monthly",
    imageUrl: "https://example.com/images/salary.jpg",
  },
  {
    id: "t005",
    type: "expense",
    category: "Giải trí",
    note: "Mua game trên Steam",
    amount: 240000,
    currency: "VND",
    date: "2025-10-09",
    repeat: "never",
    imageUrl: "https://example.com/images/game.jpg",
  },
  {
    id: "t006",
    type: "expense",
    category: "Nhà cửa",
    note: "Mua lọ hoa trang trí",
    amount: 120000,
    currency: "VND",
    date: "2025-10-07",
    repeat: "never",
    imageUrl: "https://example.com/images/vase.jpg",
  },
  {
    id: "t007",
    type: "expense",
    category: "Gia đình & Cá nhân",
    note: "Mua quà cho mẹ",
    amount: 350000,
    currency: "VND",
    date: "2025-10-08",
    repeat: "never",
    imageUrl: "https://example.com/images/gift.jpg",
  },
  {
    id: "t008",
    type: "income",
    category: "Bán đồ cũ",
    note: "Bán tai nghe cũ",
    amount: 500000,
    currency: "VND",
    date: "2025-10-11",
    repeat: "never",
    imageUrl: "https://example.com/images/used-headphone.jpg",
  },
  {
    id: "t009",
    type: "expense",
    category: "Xe cộ",
    note: "Rửa xe",
    amount: 40000,
    currency: "VND",
    date: "2025-10-12",
    repeat: "weekly",
    imageUrl: "https://example.com/images/carwash.jpg",
  },
  {
    id: "t010",
    type: "expense",
    category: "Chăm sóc sức khỏe",
    note: "Mua vitamin D3",
    amount: 250000,
    currency: "VND",
    date: "2025-10-06",
    repeat: "never",
    imageUrl: "https://example.com/images/vitamin.jpg",
  },
];


